[package]
name = "kvs"
version = "0.1.0"
authors = ["khamitov02  <khamitov02@inbox.ru>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
[dev-dependencies]
assert_cmd = "2.0.9"
predicates = "3.1.2"
